version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "deps"
    groups:
      electron:
        patterns:
          - "electron*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
